### ISSUE TITLE
Turn output on doesn't reset the timer

### ISSUE THREAD

**Issue by evilB** [openmotics/gateway#182]
I have the following special function for an input connected to a motion sensor with fixed timer of about 1 minute.

- When I pass by this sensor, the sensor closes the connection and line 00 is activated, => the light turns on
- When i leave the area, after 1 minute, the sensor opens the connection and the timer on line 02 is activated and will turn off the light in 2.5 minutes
- When I re-enter the area while the timer is active, the motion sensor executes line 00 again (but the light was already on)
- When I remain in the area for the remaining duration of the 2.5 minutes, line 02 is not executed until after i leave the area.

```
[openmotics]$ input action read 10
L1.3 -> 240 Special function
00 161 025
01 236 000
02 160 025
03 236 255
04 255 255
```

I would expect action type 161to remove the timer on output 025. (the docs contain the following message:

>  Light/Output x On (x<240, with standard timer setting, with last dimmer value)

I haven't been able to find how the standard timer setting for an output is read or adjusted so I haven't been able to test/verify if these values change.

**Comment by khenderick** [comment]
Hi,

If you're a customer, you can always mail to support@openmotics.com with technical questions. This will create a ticket in our system that can be followed-up by more people. Not everyone at OpenMotics uses GitHub :smiley:

To answer your question; the system will use the last used timer value and re-enter the timer when the output is switched off. When the output is on and you use BA 161 to switch it on again (when already ON), the timer will not be changed. To do this, you can use BA 153 that will reset the timer value even when the light is on. However, this call was introduced recently, so depending on the version you're running you might have to update your system first. I suggest to send us an email at support@openmotics.com with the first set of digits of your Gateway's registration key so we can check this out for you.

Best regards,

Kenneth
