### ISSUE TITLE
API call 'get_errors' returns empty array errors[]

### ISSUE THREAD

**Issue by d-bugger** [openmotics/gateway#39]
When calling the API get_errors, the following JSON is returned:
`{"power_last_success": 0, "errors": [], "success": true, "master_last_success": [18.03}`

The 'errors' array is empty while there actually are errors (from the cloud maintenance console):

> [openmotics]$ error list 
i2c errors: 0/0 1:1
00 I 073.132.087.255 0   No Errors
01 I 073.217.025.152 0   No Errors
02 I 073.202.073.070 0   No Errors
03 I 073.145.140.129 0   No Errors
04 I 073.014.100.017 0   No Errors
05 I 073.106.216.180 0   No Errors
06 I 073.186.138.042 0   No Errors
07 I 073.011.010.008 0   No Errors
08 T 084.100.201.146 0   # of Errors: 25158
09 T 084.031.062.125 0   # of Errors: 25140
00 O 079.247.193.086 0   No Errors
01 O 079.128.020.060 0   No Errors
02 D 068.226.197.138 0   No Errors
03 O 079.012.015.022 0   No Errors
04 O 079.178.131.037 0   No Errors
Large Installation enabled
00 R 082.140.142.145 Roller/Shutter
01 R 082.209.083.086 Roller/Shutter
02 R 082.078.095.129 Roller/Shutter

I would expect at least 2 entries in the array (for both temperature modules with errors), but preferably a list of all modules with the actual error count (0 under normal conditions)

**Comment by khenderick** [comment]
It seems this issue got out of my attention. However, it should have been resolved in the meantime. If you update your installation to the most recent version, the API call should return the expected data.
